---
title: "Untitled"
author: "Gabe Runte"
date: "2023-04-07"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(here)
library(janitor)
```



```{r}
d01 = read_csv(here("data", "sjnf_tipdissections - D01.csv")) %>% 
  rename(row = ...1) %>% 
  pivot_longer(cols = 2:13, names_to = "column", values_to = "tube_id")%>% 
  mutate(column = as.numeric(column))


tips = read_csv(here("data", "field_tips.csv")) %>% 
  pivot_longer(cols = c("rna", "dna"), names_to = "acid", values_to = "tube_id")
  # mutate(replicate = as.factor(replicate))%>% 
  # mutate(replicate = case_when(
  #   replicate == "6" ~ "Control",
  #   TRUE ~ replicate
  # ))

d01_successes = read_csv(here("data", "dissected_pcrsuccesses_D01.csv")) %>% 
  select(old_column, old_well, amp_success) %>% 
  rename(column = old_column, row = old_well) %>% 
  mutate(column = as.numeric(column))


total = d01 %>% 
  left_join(d01_successes) %>% 
  mutate(amp_success = case_when(
    is.na(amp_success) ~ 0, 
    TRUE ~ amp_success
  )) %>% 
  mutate(amp_success = as.factor(amp_success)) %>% 
  left_join(tips) %>% 
  arrange(column, row) %>% 
  mutate(position = 1:96) %>% 
  mutate(control = case_when(
    replicate == "6" ~ "yes", 
    replicate != 6 ~ "no"
  ))
```
```{r}
ggplot(total, aes(x = replicate, fill = amp_success, group = amp_success))+
  geom_bar()

ggplot(total, aes(x = tree_id, fill = amp_success, group = amp_success))+
  geom_bar()

ggplot(total, aes(x = position, y = as.numeric(amp_success), col = row))+
  geom_point()
```


```{r}
failed = total %>% 
  filter(amp_success == "0") %>% 
  select(row, column, tube_id)

write_csv(failed, here("data", "dissect_dilute.csv"))
```








